CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340bkv5;

-- Table structure for table 'classification'
CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory
(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL,
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9, 0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_color character varying NOT NULL,
	classification_id integer NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Table structure for 'upgrade'
CREATE TABLE IF NOT EXISTS public.upgrade
(
	upgrade_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	upgrade_name character varying NOT NULL,
	upgrade_description character varying NOT NULL,
  upgrade_price numeric(9, 0) NOT NULL,
	upgrade_image character varying NOT NULL,
	inv_id integer NOT NULL,
	CONSTRAINT upgrade_pkey PRIMARY KEY (upgrade_id)
);

-- Create relationship between 'classification' and 'inventory' tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Table structure for table 'account'
CREATE TABLE IF NOT EXISTS public.account
(
	account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	account_firstname character varying NOT NULL,
	account_lastname character varying NOT NULL,
	account_email character varying NOT NULL,
	account_password character varying NOT NULL,
	account_type account_type NOT NULL DEFAULT 'Client'::account_type,
	CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for table 'classification'
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');

-- Data for table `inventory`
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES   (
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
    '/images/camaro.jpg',
    '/images/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
  ), (
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.',
    '/images/batmobile.jpg',
    '/images/batmobile-tn.jpg',
    65000,
    29887,
    'Black',
    1
  ), (
    'FBI',
    'Surveillance Van',
    '2016',
    'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.',
    '/images/survan.jpg',
    '/images/survan-tn.jpg',
    20000,
    19851,
    'Brown',
    1
  ), (
    'Dog ',
    'Car',
    '1997',
    'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.',
    '/images/dog-car.jpg',
    '/images/dog-car-tn.jpg',
    35000,
    71632,
    'White',
    1
  ), (
    'Jeep',
    'Wrangler',
    '2019',
    'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!',
    '/images/wrangler.jpg',
    '/images/wrangler-tn.jpg',
    28045,
    41205,
    'Yellow',
    3
  ), (
    'Lamborghini',
    'Adventador',
    '2016',
    'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
    '/images/adventador.jpg',
    '/images/adventador-tn.jpg',
    417650,
    71003,
    'Blue',
    2
  ), (
    'Aerocar International',
    'Aerocar',
    '1963',
    'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
    '/images/aerocar.jpg',
    '/images/aerocar-tn.jpg',
    700000,
    18956,
    'Red',
    1
  ), (
    'Monster',
    'Truck',
    '1995',
    'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.',
    '/images/monster-truck.jpg',
    '/images/monster-truck-tn.jpg',
    150000,
    3998,
    'purple',
    1
  ), (
    'Cadillac',
    'Escalade',
    '2019',
    'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
    '/images/escalade.jpg',
    '/images/escalade-tn.jpg',
    75195,
    41958,
    'Black',
    4
  ), (
    'GM',
    'Hummer',
    '2016',
    'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
    '/images/hummer.jpg',
    '/images/hummer-tn.jpg',
    58800,
    56564,
    'Yellow',
    4
  ), (
    'Mechanic',
    'Special',
    '1964',
    'Not sure where this car came from. however with a little tlc it will run as good a new.',
    '/images/mechanic.jpg',
    '/images/mechanic-tn.jpg',
    100,
    200125,
    'Rust',
    5
  ), (
    'Ford',
    'Model T',
    '1921',
    'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
    '/images/model-t.jpg',
    '/images/model-t-tn.jpg',
    30000,
    26357,
    'Black',
    5
  ), (
    'Mystery',
    'Machine',
    '1999',
    'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.',
    '/images/mystery-van.jpg',
    '/images/mystery-van-tn.jpg',
    10000,
    128564,
    'Green',
    1
  ),
  (
    'Spartan',
    'Fire Truck',
    '2012',
    'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.',
    '/images/fire-truck.jpg',
    '/images/fire-truck-tn.jpg',
    50000,
    38522,
    'Red',
    4
  ), (
    'Ford',
    'Crown Victoria',
    '2013',
    'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.',
    '/images/crwn-vic.jpg',
    '/images/crwn-vic-tn.jpg',
    10000,
    108247,
    'White',
    5
  );

-- Task 4
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Task 6
UPDATE inventory
SET 
	inv_image = 
		CONCAT(
        SUBSTRING(inv_image FROM 1 FOR POSITION('/images/' IN inv_image) + LENGTH('/images/') - 1), 
        'vehicles/', 
        SUBSTRING(inv_image FROM POSITION('/images/' IN inv_image) + LENGTH('/images/'))
    ),
	inv_thumbnail =
		CONCAT(
        SUBSTRING(inv_thumbnail FROM 1 FOR POSITION('/images/' IN inv_thumbnail) + LENGTH('/images/') - 1), 
        'vehicles/', 
        SUBSTRING(inv_thumbnail FROM POSITION('/images/' IN inv_thumbnail) + LENGTH('/images/'))
    );

INSERT INTO public.upgrade (
    upgrade_name,
    upgrade_description,
    upgrade_price,
    upgrade_img,
    inv_id
)
VALUES  (
    'Grappling Hook Launcher',
    'Deploy a high-tensile grappling hook to scale buildings or make sharp turns quickly. Ideal for urban crime-fighting or navigating tricky terrain.',
    5000,
    '/images/grappling-hook.jpg',
    2
), (
    'Stealth Mode',
    'Activate advanced cloaking technology to render the Batmobile invisible to the naked eye and radar. Perfect for covert operations.',
    10000
    '/images/stealth-mode.jpg',
    2
), (
    'High-Resolution Camera System',
    State-of-the-art high-resolution cameras with night vision and 360-degree coverage for comprehensive surveillance capabilities.',
    3500,
    '/images/camera-system.jpg',
    3
), (
    'Encrypted Communication Suite',
    'Secure communication systems including encrypted radios and a satellite phone to ensure confidential information remains private.',
    2800,
    '/images/communication-suite.jpg',
    3
), (
    'Emergency Parachute',
    'Integrated emergency parachute for the entire vehicle, providing an added layer of safety during flight.',
    12000,
    '/images/emergency-parachute.jpg',
    7
), (
    'Engine Rebuild Kit',
    'Complete engine rebuild kit with new pistons, gaskets, and timing components to restore power and efficiency.',
    1200,
    '/images/rebuild-kit.jpg',
    11
), (
    'Tool Box',
    'Comprehensive tool box with essential tools for maintenance and repairs, ensuring you're always prepared for any mechanical issue.',
    300,
    '/images/tool-box.jpg',
    11
), (
    'Modern Ignition System',
    'Upgrade the original ignition system to a modern, more reliable electronic ignition, ensuring easier starts and smoother running.',
    1200,
    '/images/ignition-system.jpg',
    12
), (
    'Comfort Seating',
    'Replace the original seats with more comfortable, period-appropriate cushioned seating, enhancing driving comfort while maintaining historical accuracy.',
    1000,
    '/images/comfort-seating.jpg',
    12
), (
    'Flux Capacitor',
    'The essential upgrade for time travel enthusiasts. Allows your vehicle to travel through time when reaching 88 mph. (Note: Time travel results may vary).',
    12000,
    '/images/flux-cap-up.jpg',
    16
), (
    'Flame Decals',
    'High-quality flame decals to give your car a hot rod look. Durable and weather-resistant for a long-lasting, stylish appearance.',
    200,
    '/images/flame-decals-up.jpg',
    16
), (
    'Bumper Sticker',
    'Personalized bumper sticker with your choice of slogan or design. Adds a touch of individuality to your vehicle.',
    10,
    '/images/bump-stick-up.jpg',
    16
), (
    'Hub Caps',
    'Stylish hub caps to enhance the appearance of your wheels. Available in various designs to match your car's aesthetic.',
    100,
    '/images/hub-cap-up.jpg',
    16
), (
    'Racing Stripes',
    'Add a sporty look to your car with custom racing stripes. Available in a variety of colors to match your style.',
    300,
    '/images/racing-stripes.jpg',
    1
), (
    'Racing Seats and Harness',
    'Replace the stock seats with lightweight racing seats and a 5-point harness for better support during high-speed driving and track days. Enhances safety and driver control.',
    8500,
    '/images/racing-harness.jpg',
    6
), (
    'Offroad Suspension',
    'Upgrade your vehicle with an off-road suspension kit for improved ground clearance and better performance on rough terrain.',
    1800,
    '/images/offroad-susp.jpg',
    5
), (
    'LED Light Bar',
    'Improve visibility during night-time off-roading with a high-intensity LED light bar. Ensures you can see and be seen in any conditions.',
    750,
    '/images/light-bar.jpg',
    5
), (
    'Bulletproof Windows and Body',
    'Upgrade to bulletproof glass and reinforced body panels for enhanced protection. Provides safety and peace of mind in any situation.',
    20000,
    '/images/bulletproof.jpg',
    9
);